export const selectItems = ["All", "Simple", "Mid", "Pro"];
export const workItems = [
  {
    label: "Apple",
    level: "Simple",
    img: "apple.png",
    link: "https://n4jari.github.io/apple",
    description: "React JS",
    id: 1,
  },
  {
    label: "Nike",
    img: "nike.png",
    link: "https://n4jari.github.io/nike",
    description: "React JS",
    id: 2,
  },
  {
    label: "BBC",
    level: "Simple",
    img: "bbc.png",
    link: "https://n4jari.github.io/bbc",
    description: "React JS",
    id: 3,
  },
  {
    label: "TechLand",
    level: "Simple",
    img: "techland.png",
    link: "https://n4jari.github.io/techland",
    description: "React JS - Bootstrap",
    id: 4,
  },
  {
    label: "Amilo",
    level: "Simple",
    img: "amilo.png",
    link: "https://n4jari.github.io/amilo",
    description: "React JS",
    id: 5,
  },
  {
    label: "Todo",
    level: "Mid",
    img: "todo.png",
    link: "https://n4jari.github.io/todo-app",
    description: "React JS - Material UI - Context API",
    id: 6,
  },
  {
    label: "Students Management",
    level: "Mid",
    img: "students.png",
    link: "https://n4jari.github.io/students-management",
    description: "React JS - Bootstrap - Json Server - Formik & Yup - Context API",
    id: 7,
  },
  {
    label: "Portfolio",
    level: "Mid",
    img: "portfolio.png",
    link: "https://n4jari.github.io/portfolio",
    description: "React JS - Material UI - Json Server - Formik & Yup - Context API",
    id: 8,
  },
  {
    label: "Sky Wallet",
    level: "Mid",
    img: "skywallet.png",
    link: "https://sky-wallet.vercel.app",
    description: "Next JS - Typescript - Tailwind - Json Server - Context API",
    id: 9,
  },
  {
    label: "Quiz App",
    level: "Mid",
    img: "quiz.png",
    link: "https://quiz-app-nine-wine.vercel.app",
    description: "Next JS - TypeScript - Context API",
    id: 10,
  }, 
  {
    label: "Admin dashboard",
    level: "Pro",
    img: "admin.png",
    link: "https://admin-two-virid.vercel.app/",
    description: "Next JS - Mongo Atlas - Mongoose - Tailwind - Context API",
    id: 10,
  },
];
